uploads = []
outputs = []

[[generated]]
id = "HkyVJDRnEPv7uxXKYCpeN"
uri = "file://artifacts/cybershield/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UzoUY4ahEZqPYnQJf7C4Y"
uri = "file://artifacts/cybershield/assets/images/splash.png"
type = "image"
title = "generated_image"
